Format function in renderCell
xavi-tristancho/neoadmin pull request #125
Opened 2023-11-12 18:00 UTC by vallejofran

2023-11-14 16:10 UTC, xavi-tristancho requested changes

2023-11-17 16:48 UTC, vallejofran commented
No able to render together both input cell and select options as objects in category element on second commit

2023-11-19 10:33 UTC, xavi-tristancho requested changes

2023-11-19 10:33 UTC, xavi-tristancho commented on apps/demo/src/pages/Posts/headers.tsx
> +          },
Para el proyecto demo, el único campo que necesita tener definida la función `format`, tiene que ser el campo imagen.

2023-11-19 10:33 UTC, xavi-tristancho commented on apps/demo/src/pages/Posts/headers.tsx
> +// import renderCellExpand from '@app-artisans/backoffice/src/components/ModelTable/components/RenderCellExpand';
Elimina el comentario

2023-11-19 10:33 UTC, xavi-tristancho commented on packages/backoffice/src/components/ModelTable/utils.ts
> +          : {}),
El código debería ser genérico, ¿seguro que necesitamos estos casos?

2023-11-19 10:33 UTC, xavi-tristancho commented on packages/backoffice/src/components/ModelTable/utils.ts
> +import { RenderCellExpand } from "./components";
¿Para qué necesitamos este componente?

2023-11-19 10:33 UTC, xavi-tristancho commented on packages/backoffice/src/components/ModelTable/utils.ts
> +                  category: getRow(item, props).category,
¡Esto está bastante bien! Si cambiamos la key `category` por `item` lo hacemos genérico.

2023-11-19 21:59 UTC, vallejofran commented on packages/backoffice/src/components/ModelTable/utils.ts
> +import { RenderCellExpand } from "./components";
Ok, la ocultare pues, desde un inicio no tenia claro si las columnas a renderizar "con ciertos estilos", eran todas o unicamente la imagen con el etiquetado que indicaste en el ticket..

2023-11-19 22:34 UTC, vallejofran commented on packages/backoffice/src/components/ModelTable/utils.ts
> +                  category: getRow(item, props).category,
Aqui me gustaria entender a que te refieres, la prop categoy se la estoy pasando a la funcion format definida para la columna category en los headers, y comentas que ya no la deben tener a excepcion de la imagen...

2023-11-27 15:39 UTC, xavi-tristancho requested changes

2023-11-28 21:48 UTC, vallejofran commented on packages/backoffice/src/components/ModelTable/utils.ts
> +                  category: getRow(item, props).category,
Ok, es que no tenia claro y dudo, de si el proyecto es un back office en si, el cual vendeis o dais servicio etc... o si se trata de una libreria de dependencias con componentes para desarrollar el back office en React.. :(
Ejecute la landing y eso vi por alli, entonces ya no entendia nada, sorry, pero es que desconocia por completo el proyecto

2023-12-15 20:37 UTC, xavi-tristancho approved these changes

2023-12-15 20:39 UTC, merged